@echo off
setlocal EnableDelayedExpansion

REM ==========================================
REM CONFIGURATION (Cấu hình đường dẫn tại đây)
REM ==========================================
SET "TOMCAT_HOME=C:\tomcat"
SET "TOMCAT_PORT=8080"
SET "WEBAPPS_FOLDER=%TOMCAT_HOME%\webapps"
SET "LOCALHOST_URL=http://localhost:%TOMCAT_PORT%"
TITLE Tomcat Manager - Port %TOMCAT_PORT%

REM Kiểm tra đường dẫn Tomcat hợp lệ
IF NOT EXIST "%TOMCAT_HOME%" (
    color 0C
    echo [ERROR] Khong tim thay thu muc Tomcat tai: %TOMCAT_HOME%
    echo Vui long chinh sua lai bien TOMCAT_HOME trong file script nay.
    pause
    EXIT
)

:MENU
cls
color 0B
echo ==================================================
echo        APACHE TOMCAT CONTROL PANEL (ADVANCED)
echo ==================================================
echo.
call :CHECK_STATUS
echo.
echo   1. Start Tomcat Server
echo   2. Stop Tomcat Server
echo   3. Restart Tomcat Server
echo   4. Create New Project (Auto Scaffold)
echo   5. Open Webapps Root Folder
echo   6. Open Localhost in Browser
echo   7. Check Port %TOMCAT_PORT% Details
echo   0. Exit
echo.
set /p choice=Chon chuc nang [0-7]: 

IF "%choice%"=="1" GOTO START_SERVER
IF "%choice%"=="2" GOTO STOP_SERVER
IF "%choice%"=="3" GOTO RESTART_SERVER
IF "%choice%"=="4" GOTO CREATE_PROJECT
IF "%choice%"=="5" GOTO OPEN_WEBAPPS
IF "%choice%"=="6" GOTO OPEN_LOCALHOST
IF "%choice%"=="7" GOTO CHECK_PORT_DETAIL
IF "%choice%"=="0" EXIT

goto MENU

REM ==========================================
REM FUNCTIONS
REM ==========================================

:CHECK_STATUS
    netstat -ano | findStr ":%TOMCAT_PORT% " | findStr "LISTENING" >nul
    if %errorlevel%==0 (
        echo   STATUS: [ ONLINE ] - Port %TOMCAT_PORT% dang hoat dong.
        set "SERVER_STATUS=RUNNING"
    ) else (
        echo   STATUS: [ OFFLINE ] - Port %TOMCAT_PORT% dang trong.
        set "SERVER_STATUS=STOPPED"
    )
    goto :eof

:START_SERVER
    cls
    call :CHECK_STATUS
    if "%SERVER_STATUS%"=="RUNNING" (
        color 0E
        echo [WARNING] Server dang chay hoac Port %TOMCAT_PORT% bi chiem dung.
        echo Vui long kiem tra lai hoac dung chuc nang Restart.
        pause
        goto MENU
    )
    
    echo ------------------------------------------
    echo Starting Apache Tomcat...
    echo ------------------------------------------
    cd /d "%TOMCAT_HOME%\bin"
    
    REM Start trong cua so moi de khong bi treo script
    start "Apache Tomcat" call catalina.bat start
    
    echo Dang khoi dong... vui long cho 5-10 giay.
    timeout /t 5 >nul
    echo Done.
    goto MENU

:STOP_SERVER
    cls
    echo ------------------------------------------
    echo Stopping Apache Tomcat...
    echo ------------------------------------------
    cd /d "%TOMCAT_HOME%\bin"
    call shutdown.bat
    echo Gui lenh Stop thanh cong.
    timeout /t 3 >nul
    goto MENU

:RESTART_SERVER
    cls
    echo [1/2] Dang tat Server...
    call :STOP_SERVER
    echo.
    echo [2/2] Dang bat lai Server...
    timeout /t 3 >nul
    goto START_SERVER

:CHECK_PORT_DETAIL
    cls
    echo ------------------------------------------
    echo Kiem tra tien trinh chiem dung Port %TOMCAT_PORT%
    echo ------------------------------------------
    netstat -ano | findStr ":%TOMCAT_PORT%"
    echo.
    echo NOTE: Cot cuoi cung la PID (Process ID).
    echo Ban co the dung Task Manager de kill PID nay neu can.
    pause
    goto MENU

:CREATE_PROJECT
    cls
    echo ==========================================
    echo        CREATE NEW WEB PROJECT
    echo ==========================================
    echo.
    set /p projName=Nhap ten Project (khong dau, khong khoang trang): 
    
    IF "%projName%"=="" goto MENU
    IF EXIST "%WEBAPPS_FOLDER%\%projName%" (
        echo [ERROR] Project "%projName%" da ton tai!
        pause
        goto MENU
    )

    echo Creating directory...
    mkdir "%WEBAPPS_FOLDER%\%projName%"
    
    echo Creating default index.jsp...
    (
        echo ^<html^>
        echo ^<head^>^<title^>%projName%^</title^>^</head^>
        echo ^<body^>
        echo    ^<h1^>Project: %projName% Created Successfully!^</h1^>
        echo    ^<p^>Tomcat Server is running.^</p^>
        echo    ^<hr^>
        echo    ^<i^>Generated by Script^</i^>
        echo ^</body^>
        echo ^</html^>
    ) > "%WEBAPPS_FOLDER%\%projName%\index.jsp"

    echo.
    echo [SUCCESS] Project da duoc tao tai: %WEBAPPS_FOLDER%\%projName%
    echo Opening folder...
    start "" "%WEBAPPS_FOLDER%\%projName%"
    
    echo.
    echo Ban co the truy cap tai: %LOCALHOST_URL%/%projName%
    pause
    goto MENU

:OPEN_WEBAPPS
    start "" "%WEBAPPS_FOLDER%"
    goto MENU

:OPEN_LOCALHOST
    start "" "%LOCALHOST_URL%"
    goto MENU
