@echo off
@chcp 65001 >nul
setlocal EnableDelayedExpansion

REM ==========================================
REM CONFIGURATION (Cấu hình đường dẫn tại đây)
REM ==========================================
SET "TOMCAT_HOME=C:\tomcat"
SET "TOMCAT_PORT=8080"
SET "WEBAPPS_FOLDER=%TOMCAT_HOME%\webapps"
SET "LOCALHOST_URL=http://localhost:%TOMCAT_PORT%"
TITLE Tomcat Manager - Port %TOMCAT_PORT%

REM Kiểm tra đường dẫn Tomcat hợp lệ
IF NOT EXIST "%TOMCAT_HOME%" (
    color 0C
    echo [ERROR] Không tìm thấy thư mục Tomcat tại: %TOMCAT_HOME%
    echo Vui lòng chỉnh sửa lại biến TOMCAT_HOME trong file script này.
    pause
    EXIT
)

:MENU
cls
color 0B
echo ==================================================
echo        APACHE TOMCAT CONTROL PANEL (ADVANCED)
echo ==================================================
echo.
call :CHECK_STATUS
echo.
echo   1. Start Tomcat Server
echo   2. Stop Tomcat Server
echo   3. Restart Tomcat Server
echo   4. Create New Project (Auto Scaffold)
echo   5. Open Webapps Root Folder
echo   6. Open Localhost in Browser
echo   7. Check Port %TOMCAT_PORT% Details
echo   8. Scan Webapps
echo   0. Exit
echo.
set /p choice=Chọn chức năng [0-8]: 

IF "%choice%"=="1" GOTO START_SERVER
IF "%choice%"=="2" GOTO STOP_SERVER
IF "%choice%"=="3" GOTO RESTART_SERVER
IF "%choice%"=="4" GOTO CREATE_PROJECT
IF "%choice%"=="5" GOTO OPEN_WEBAPPS
IF "%choice%"=="6" GOTO OPEN_LOCALHOST
IF "%choice%"=="7" GOTO CHECK_PORT_DETAIL
IF "%choice%"=="8" GOTO SCAN_WEBAPPS
IF "%choice%"=="0" EXIT

goto MENU

REM ==========================================
REM FUNCTIONS
REM ==========================================

:CHECK_STATUS
    netstat -ano | findStr ":%TOMCAT_PORT% " | findStr "LISTENING" >nul
    if %errorlevel%==0 (
        echo   STATUS: [ ONLINE ] - Port %TOMCAT_PORT% đang hoạt động.
        set "SERVER_STATUS=RUNNING"
    ) else (
        echo   STATUS: [ OFFLINE ] - Port %TOMCAT_PORT% đang trống.
        set "SERVER_STATUS=STOPPED"
    )
    goto :eof

:START_SERVER
    cls
    call :CHECK_STATUS
    if "%SERVER_STATUS%"=="RUNNING" (
        color 0E
        echo [WARNING] Server đang chạy hoặc Port %TOMCAT_PORT% bị chiếm dụng.
        echo Vui lòng kiểm tra lại hoặc dùng chức năng Restart.
        pause
        goto MENU
    )
    
    echo ------------------------------------------
    echo Starting Apache Tomcat...
    echo ------------------------------------------
    cd /d "%TOMCAT_HOME%\bin"
    
    REM Start trong cửa sổ mới
    start "Apache Tomcat" call catalina.bat start
    
    echo Đang khởi động... vui lòng chờ 5-10 giây.
    timeout /t 5 >nul
    echo Done.
    goto MENU

:STOP_SERVER
    cls
    echo ------------------------------------------
    echo Stopping Apache Tomcat...
    echo ------------------------------------------
    cd /d "%TOMCAT_HOME%\bin"
    call shutdown.bat
    echo Gửi lệnh Stop thành công.
    timeout /t 3 >nul
    goto MENU

:RESTART_SERVER
    cls
    echo [1/2] Đang tắt Server...
    call :STOP_SERVER
    echo.
    echo [2/2] Đang bật lại Server...
    timeout /t 3 >nul
    goto START_SERVER

:CHECK_PORT_DETAIL
    cls
    echo ------------------------------------------
    echo Kiểm tra tiến trình chiếm dụng Port %TOMCAT_PORT%
    echo ------------------------------------------
    netstat -ano | findStr ":%TOMCAT_PORT%"
    echo.
    echo NOTE: Cột cuối cùng là PID (Process ID).
    echo Bạn có thể dùng Task Manager để kill PID này nếu cần.
    pause
    goto MENU

:CREATE_PROJECT
    cls
    echo ==========================================
    echo        CREATE NEW WEB PROJECT
    echo ==========================================
    echo.
    set /p projName=Nhập tên Project (không dấu, không khoảng trắng): 
    
    IF "%projName%"=="" goto MENU
    IF EXIST "%WEBAPPS_FOLDER%\%projName%" (
        echo [ERROR] Project "%projName%" đã tồn tại!
        pause
        goto MENU
    )

    echo Creating directory...
    mkdir "%WEBAPPS_FOLDER%\%projName%"
    
    echo Creating default index.jsp...
    (
        echo ^<html^>
        echo ^<head^>^<title^>%projName%^</title^>^</head^>
        echo ^<body^>
        echo    ^<h1^>Project: %projName% Created Successfully!^</h1^>
        echo    ^<p^>Tomcat Server is running.^</p^>
        echo    ^<hr^>
        echo    ^<i^>Generated by Script^</i^>
        echo ^</body^>
        echo ^</html^>
    ) > "%WEBAPPS_FOLDER%\%projName%\index.jsp"

    echo.
    echo [SUCCESS] Project đã được tạo tại: %WEBAPPS_FOLDER%\%projName%
    echo Opening folder...
    
    REM Dùng explorer an toàn hơn start
    explorer "%WEBAPPS_FOLDER%\%projName%"
    
    echo.
    echo Bạn có thể truy cập tại: %LOCALHOST_URL%/%projName%
    pause
    goto MENU

:SCAN_WEBAPPS
    cls
    echo ==========================================
    echo        DANH SÁCH PROJECT (WEBAPPS)
    echo ==========================================
    echo.
    set "cnt=0"
    
    REM Loop qua tất cả thư mục trong webapps
    for /d %%D in ("%WEBAPPS_FOLDER%\*") do (
        set /a cnt+=1
        set "PROJ_!cnt!=%%~nxD"
        echo   !cnt!. %%~nxD
    )
    
    if !cnt!==0 (
        echo [INFO] Không tìm thấy project nào trong thư mục webapps.
        pause
        goto MENU
    )
    
    echo.
    set /p pChoice=Nhập số thứ tự để mở (0 để quay lại): 
    
    if "%pChoice%"=="0" goto MENU
    
    REM Kiểm tra input hợp lệ
    if %pChoice% GTR !cnt! (
        echo [ERROR] Lựa chọn không hợp lệ!
        pause
        goto SCAN_WEBAPPS
    )
    if %pChoice% LSS 1 (
        echo [ERROR] Lựa chọn không hợp lệ!
        pause
        goto SCAN_WEBAPPS
    )

    REM Lấy tên project từ biến mảng giả lập
    set "TARGET_PROJ=!PROJ_%pChoice%!"
    
    echo.
    echo Opening Browser: %LOCALHOST_URL%/!TARGET_PROJ! ...
    REM Dùng explorer để mở URL
    explorer "%LOCALHOST_URL%/!TARGET_PROJ!"
    
    echo Opening Folder: %WEBAPPS_FOLDER%\!TARGET_PROJ! ...
    REM Dùng explorer để mở thư mục
    explorer "%WEBAPPS_FOLDER%\!TARGET_PROJ!"
    
    goto MENU

:OPEN_WEBAPPS
    echo Opening Webapps Folder...
    explorer "%WEBAPPS_FOLDER%"
    goto MENU

:OPEN_LOCALHOST
    echo Opening Localhost...
    explorer "%LOCALHOST_URL%"
    goto MENU
