@echo off
setlocal EnableDelayedExpansion

REM ==========================================
REM CAU HINH MAC DINH (SE DUOC GHI DE BOI .ENV)
REM ==========================================
SET "TOMCAT_HOME=C:\tomcat"
SET "TOMCAT_PORT=8080"

REM Doc file .env neu ton tai
IF EXIST ".env" (
    FOR /F "usebackq tokens=1* delims==" %%A IN (".env") DO (
        SET "%%A=%%B"
    )
)

SET "WEBAPPS_FOLDER=%TOMCAT_HOME%\webapps"
SET "LOCALHOST_URL=http://localhost:%TOMCAT_PORT%"
TITLE Tomcat Manager - Port %TOMCAT_PORT%

REM Kiem tra duong dan Tomcat hop le
IF NOT EXIST "%TOMCAT_HOME%" (
    color 0C
    echo [LOI] Khong tim thay thu muc Tomcat tai: %TOMCAT_HOME%
    echo.
    echo Ban co muon cap nhat duong dan ngay bay gio khong?
    set /p "update_now=Nhap Y de cap nhat, N de thoat: "
    IF /I "!update_now!"=="Y" (
        GOTO EDIT_CONFIG
    ) ELSE (
        EXIT
    )
)

:MENU
cls
color 0B
echo ==================================================
echo        APACHE TOMCAT CONTROL PANEL (NO ACCENT)
echo ==================================================
echo.
call :CHECK_STATUS
echo.
echo    1. Bat Tomcat Server (Start)
echo    2. Tat Tomcat Server (Stop)
echo    3. Khoi dong lai Server (Restart)
echo    4. Tao Project moi (Tu dong tao folder/file)
echo    5. Mo thu muc Webapps
echo    6. Mo Localhost tren trinh duyet
echo    7. Kiem tra tien trinh Port %TOMCAT_PORT%
echo    8. Quet danh sach Webapps
echo    9. Cau hinh duong dan Tomcat (Sua .env)
echo    0. Thoat
echo.
set /p choice=Chon chuc nang [0-9]: 

IF "%choice%"=="1" GOTO START_SERVER
IF "%choice%"=="2" GOTO STOP_SERVER
IF "%choice%"=="3" GOTO RESTART_SERVER
IF "%choice%"=="4" GOTO CREATE_PROJECT
IF "%choice%"=="5" GOTO OPEN_WEBAPPS
IF "%choice%"=="6" GOTO OPEN_LOCALHOST
IF "%choice%"=="7" GOTO CHECK_PORT_DETAIL
IF "%choice%"=="8" GOTO SCAN_WEBAPPS
IF "%choice%"=="9" GOTO EDIT_CONFIG
IF "%choice%"=="0" EXIT

goto MENU

REM ==========================================
REM CAC HAM CHUC NANG (FUNCTIONS)
REM ==========================================

:CHECK_STATUS
    netstat -ano | findStr ":%TOMCAT_PORT% " | findStr "LISTENING" >nul
    if %errorlevel%==0 (
        echo    TRANG THAI: [ ONLINE ] - Port %TOMCAT_PORT% dang hoat dong.
        set "SERVER_STATUS=RUNNING"
    ) else (
        echo    TRANG THAI: [ OFFLINE ] - Port %TOMCAT_PORT% dang trong.
        set "SERVER_STATUS=STOPPED"
    )
    goto :eof

:START_SERVER
    cls
    call :CHECK_STATUS
    if "%SERVER_STATUS%"=="RUNNING" (
        color 0E
        echo [CANH BAO] Server dang chay hoac Port %TOMCAT_PORT% bi chiem dung.
        echo Vui long kiem tra lai hoac dung chuc nang Restart.
        pause
        goto MENU
    )
    
    echo ------------------------------------------
    echo Dang khoi dong Apache Tomcat...
    echo ------------------------------------------
    cd /d "%TOMCAT_HOME%\bin"
    
    REM Start trong cua so moi
    start "Apache Tomcat" call catalina.bat start
    
    echo Vui long cho 5-10 giay...
    timeout /t 5 >nul
    echo Hoan tat.
    goto MENU

:STOP_SERVER
    cls
    echo ------------------------------------------
    echo Dang tat Apache Tomcat...
    echo ------------------------------------------
    cd /d "%TOMCAT_HOME%\bin"
    call shutdown.bat
    echo Da gui lenh Stop thanh cong.
    timeout /t 3 >nul
    goto MENU

:RESTART_SERVER
    cls
    echo [1/2] Dang tat Server...
    call :STOP_SERVER
    echo.
    echo [2/2] Dang bat lai Server...
    timeout /t 3 >nul
    goto START_SERVER

:CHECK_PORT_DETAIL
    cls
    echo ------------------------------------------
    echo Kiem tra tien trinh chiem dung Port %TOMCAT_PORT%
    echo ------------------------------------------
    netstat -ano | findStr ":%TOMCAT_PORT%"
    echo.
    echo GHI CHU: Cot cuoi cung la PID (Process ID).
    echo Ban co the dung Task Manager de kill PID nay neu can.
    pause
    goto MENU

:CREATE_PROJECT
    cls
    echo ==========================================
    echo        TAO PROJECT WEB MOI
    echo ==========================================
    echo.
    set /p projName=Nhap ten Project (khong dau, khong khoang trang): 
    
    IF "%projName%"=="" goto MENU
    IF EXIST "%WEBAPPS_FOLDER%\%projName%" (
        echo [LOI] Project "%projName%" da ton tai!
        pause
        goto MENU
    )

    echo Creating directory...
    mkdir "%WEBAPPS_FOLDER%\%projName%"
    
    echo Creating default index.jsp...
    (
        echo ^<html^>
        echo ^<head^>^<title^>%projName%^</title^>^</head^>
        echo ^<body^>
        echo    ^<h1^>Project: %projName% Created Successfully!^</h1^>
        echo    ^<p^>Tomcat Server is running.^</p^>
        echo    ^<hr^>
        echo    ^<i^>Generated by Script^</i^>
        echo ^</body^>
        echo ^</html^>
    ) > "%WEBAPPS_FOLDER%\%projName%\index.jsp"

    echo.
    echo [THANH CONG] Project da duoc tao tai: %WEBAPPS_FOLDER%\%projName%
    echo Dang mo thu muc...
    
    explorer "%WEBAPPS_FOLDER%\%projName%"
    
    echo.
    echo Ban co the truy cap tai: %LOCALHOST_URL%/%projName%
    pause
    goto MENU

:SCAN_WEBAPPS
    cls
    echo ==========================================
    echo        DANH SACH PROJECT (WEBAPPS)
    echo ==========================================
    echo.
    set "cnt=0"
    
    REM Loop qua tat ca thu muc trong webapps
    for /d %%D in ("%WEBAPPS_FOLDER%\*") do (
        set /a cnt+=1
        set "PROJ_!cnt!=%%~nxD"
        echo    !cnt!. %%~nxD
    )
    
    if !cnt!==0 (
        echo [THONG BAO] Khong tim thay project nao trong thu muc webapps.
        pause
        goto MENU
    )
    
    echo.
    set /p pChoice=Nhap so thu tu de mo (0 de quay lai): 
    
    if "%pChoice%"=="0" goto MENU
    
    REM Kiem tra input hop le
    if %pChoice% GTR !cnt! (
        echo [LOI] Lua chon khong hop le!
        pause
        goto SCAN_WEBAPPS
    )
    if %pChoice% LSS 1 (
        echo [LOI] Lua chon khong hop le!
        pause
        goto SCAN_WEBAPPS
    )

    REM Lay ten project tu bien mang
    set "TARGET_PROJ=!PROJ_%pChoice%!"
    
    echo.
    echo Dang mo Trinh duyet: %LOCALHOST_URL%/!TARGET_PROJ! ...
    explorer "%LOCALHOST_URL%/!TARGET_PROJ!"
    
    echo Dang mo Thu muc: %WEBAPPS_FOLDER%\!TARGET_PROJ! ...
    explorer "%WEBAPPS_FOLDER%\!TARGET_PROJ!"
    
    goto MENU

:OPEN_WEBAPPS
    echo Dang mo thu muc Webapps...
    explorer "%WEBAPPS_FOLDER%"
    goto MENU

:OPEN_LOCALHOST
    echo Dang mo Localhost...
    explorer "%LOCALHOST_URL%"
    goto MENU

:EDIT_CONFIG
    cls
    echo ==========================================
    echo        CAU HINH TOMCAT (.ENV)
    echo ==========================================
    echo.
    echo Duong dan hien tai: %TOMCAT_HOME%
    echo Port hien tai:      %TOMCAT_PORT%
    echo.
    echo Nhap duong dan thu muc Tomcat moi (VD: D:\Tools\ApacheTomcat)
    set /p "NEW_HOME=Duong dan moi (De trong de giu nguyen): "
    
    IF NOT "!NEW_HOME!"=="" SET "TOMCAT_HOME=!NEW_HOME!"
    
    echo.
    echo Nhap Port moi (VD: 8081)
    set /p "NEW_PORT=Port moi (De trong de giu nguyen): "
    
    IF NOT "!NEW_PORT!"=="" SET "TOMCAT_PORT=!NEW_PORT!"
    
    REM Cap nhat cac bien phu thuoc
    SET "WEBAPPS_FOLDER=%TOMCAT_HOME%\webapps"
    SET "LOCALHOST_URL=http://localhost:%TOMCAT_PORT%"
    
    REM Luu vao file .env
    (
        echo TOMCAT_HOME=!TOMCAT_HOME!
        echo TOMCAT_PORT=!TOMCAT_PORT!
    ) > ".env"
    
    echo.
    echo [THANH CONG] Da luu cau hinh vao file .env
    echo Tu gio ban khong can chinh sua file bat nua.
    pause
    goto MENU
